FROM node:24-alpine

# Install Nest CLI globally
RUN npm install -g @nestjs/cli

WORKDIR /usr/src/app

# Expose NestJS default port
EXPOSE 3000

# Entrypoint: scaffold if needed, install deps, start
ENTRYPOINT ["sh", "-c", "\
    if [ ! -f package.json ]; then \
    nest new . --directory . --skip-git --package-manager npm; \
    fi; \
    npm install; \
    npm run start:dev\
    "]